lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    set_cookies:
        jwt_token:
            lifetime: 3600
            samesite: strict
            path: /
            domain: ~
            secure: false   # passer à true en production (HTTPS)
            httpOnly: true
    token_extractors:
        cookie:
            enabled: true
            name: jwt_token
